### ISSUE TITLE
Error: Exception in thread Thread-5 (worker):

### ISSUE THREAD

**Issue by drago87** [runew0lf/RuinedFooocus#117]
Was doing some img2img then removed the image but forgot to remove the `Cheat Code` img2img and got this error

```
Exception in thread Thread-5 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\AI\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\async_worker.py", line 323, in worker
    handler(task)
  File "D:\AI\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\async_worker.py", line 56, in handler
    process(gen_data)
  File "D:\AI\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\async_worker.py", line 138, in process
    width = gen_data["input_image"].width
AttributeError: 'NoneType' object has no attribute 'width'
```

**Comment by yownas** [comment]
This should be fixed now.
