### ISSUE TITLE
UnicodeDecodeError: 'cp949'?

### ISSUE THREAD

**Issue by dispather** [runew0lf/RuinedFooocus#137]
I've benn using ruinedfooocus from stablematrix. 
but, I met this error message 1 week ago,
I don't know why it pops up. Can you show me how to solve it?

full log here.
----
C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
RuinedFooocus version: 1.39.0
Comfy Backend update check complete.
Installing requirements
Total VRAM 24564 MB, total RAM 65438 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A5000 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading base model: sd_xl_base_1.0_0.9vae.safetensors
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
adding something rare to the prompt
Nice! adding something legendary to the prompt
Critical hit! Something unique has been added to the prompt
Critical hit! Something unique has been added to the prompt
(abstract art designed by João Artur da Silva:0.9) and (Barry McGee:1.2) , Vamberk Lace of a Wild berry bush, from inside a Caracol, Thunderstorm, Modern Art, F/1.8
Traceback (most recent call last):
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\venv\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\webui.py", line 163, in generate_clicked
    yield update_clicked()
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\webui.py", line 101, in update_clicked
    hint_text: gr.update(visible=True, value=modules.hints.get_hint()),
  File "C:\Users\mightyhun\AppData\Roaming\StabilityMatrix\Packages\RuinedFooocus\modules\hints.py", line 11, in get_hint
    lines = open(hintfile).read().splitlines()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xcf in position 1021: illegal multibyte sequence
--- end of message

**Comment by runew0lf** [comment]
easy fix, dont use stability matrix to install it
