### ISSUE TITLE
Problem with update or reinstallation in Stability matrix

### ISSUE THREAD

**Issue by CodersLabAt** [runew0lf/RuinedFooocus#162]
I´ve tried to update the app and as a result I get this issue:

Unpacking resources
Unpacking resources
Download Complete

Usage:   
  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] <archive url/path> ...

no such option: --extra-index-url https://download.pytorch.org/whl/cu121
Could not install RuinedFooocus (StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 2: '\r\nUsage:   \r\n  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...\r\n  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...\r\n  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] [-e] <vcs project url> ...\r\n  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] [-e] <local project path> ...\r\n  C:\Users\user\Documents\StabilityMatrix-win-x64\Data\Packages\RuinedFooocus\venv\Scripts\python.exe -m pip install [options] <archive url/path> ...\r\n\r\nno such option: --extra-index-url https://download.pytorch.org/whl/cu121\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.RuinedFooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.RuinedFooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))

**Comment by yownas** [comment]
We made a bunch of changes to how RuinedFooocus updates itself and I pushed those to the main-branch just now.
Please try again and see if it works.

**Comment by tazztone** [comment]
i just installed the dev branch and launched it successfully using the new stability matrix version
