### ISSUE TITLE
Exception in thread Thread-2 (Worker)

### ISSUE THREAD

**Issue by jordanbr20** [runew0lf/RuinedFooocus#169]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\USER\Desktop\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\async_worker.py", line 34, in worker
    import modules.pipelines
  File "C:\Users\USER\Desktop\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\pipelines.py", line 4, in <module>
    import modules.sdxl_pipeline as sdxl_pipeline
  File "C:\Users\USER\Desktop\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\sdxl_pipeline.py", line 34, in <module>
    from comfy.sample import (
ImportError: cannot import name 'convert_cond' from 'comfy.sample' (C:\Users\USER\Desktop\RuinedFooocus_win64_1-25-2\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sample.py)
Running on local URL:  http://127.0.0.1:7861

**Comment by jordanbr20** [comment]
Fresh install, extracted, batch didn't work so replaced the below, right run as admin, get this.

.\python_embeded\python.exe -s .\RuinedFooocus\entry_with_update.py

C:\Users\USER\Desktop\RuinedFooocus_win64_1-25-2\python_embeded\python.exe -s C:\Users\USER\Desktop\RuinedFooocus_win64_1-25-2\RuinedFooocus\entry_with_update.py

**Comment by yownas** [comment]
Hm. Can you try moving the folder somewhere that isn't under c:\Users\USER? I've seen people having issues having their webui's there. Making a folder like c:\AI should work fine.
