### ISSUE TITLE
Can't install, run bat ends with error

### ISSUE THREAD

**Issue by Xerxos1980** [runew0lf/RuinedFooocus#187]
Traceback (most recent call last):
  File "D:\Tools\RuinedFooocus_win64_1-25-2\RuinedFooocus\entry_with_update.py", line 49, in <module>
    from launch import *
  File "D:\Tools\RuinedFooocus_win64_1-25-2\RuinedFooocus\launch.py", line 163, in <module>
    from webui import *
  File "D:\Tools\RuinedFooocus_win64_1-25-2\RuinedFooocus\webui.py", line 21, in <module>
    import ui_controlnet
  File "D:\Tools\RuinedFooocus_win64_1-25-2\RuinedFooocus\ui_controlnet.py", line 11, in <module>
    import ui_llama
  File "D:\Tools\RuinedFooocus_win64_1-25-2\RuinedFooocus\ui_llama.py", line 3, in <module>
    from llama_cpp import Llama
  File "D:\Tools\RuinedFooocus_win64_1-25-2\python_embeded\lib\site-packages\llama_cpp\__init__.py", line 2, in <module>
    from .llama import *
  File "D:\Tools\RuinedFooocus_win64_1-25-2\python_embeded\lib\site-packages\llama_cpp\llama.py", line 35, in <module>
    from .llama_cache import (
  File "D:\Tools\RuinedFooocus_win64_1-25-2\python_embeded\lib\site-packages\llama_cpp\llama_cache.py", line 10, in <module>
    import diskcache
ModuleNotFoundError: No module named 'diskcache'

**Comment by yownas** [comment]
Should be fixed in https://github.com/runew0lf/RuinedFooocus/commit/bf2fc2e96055e0b9fe20e69523373c4bdb1494c4
(Will be merged into main soon)
