### ISSUE TITLE
Cant find where to put token for IMG2STL

### ISSUE THREAD

**Issue by Pajamas720** [runew0lf/RuinedFooocus#190]
title. i followed https://github.com/runew0lf/RuinedFooocus/discussions/183 up until step 3. i cant find where to put the token and the guide doesnt say anything at all on this.

**Comment by Pajamas720** [comment]
edit: I installed huggingface_hub but it isnt recognized as a command i can use.

**Comment by Pajamas720** [comment]
I managed to get to a point where i could enter the tokeninto python, but then was met with the following error:

Enter your token (input will not be visible):
Add token as git credential? (Y/n) y
Token is valid (permission: read).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PJFiles\Asset_Modeler\SDImageAi\RuinedFooocus\python_embeded\lib\site-packages\huggingface_hub\_login.py", line 115, in login
    interpreter_login(new_session=new_session, write_permission=write_permission)
  File "C:\PJFiles\Asset_Modeler\SDImageAi\RuinedFooocus\python_embeded\lib\site-packages\huggingface_hub\_login.py", line 194, in interpreter_login
    _login(token=token, add_to_git_credential=add_to_git_credential, write_permission=write_permission)
  File "C:\PJFiles\Asset_Modeler\SDImageAi\RuinedFooocus\python_embeded\lib\site-packages\huggingface_hub\_login.py", line 316, in _login
    if _is_git_credential_helper_configured():
  File "C:\PJFiles\Asset_Modeler\SDImageAi\RuinedFooocus\python_embeded\lib\site-packages\huggingface_hub\_login.py", line 357, in _is_git_credential_helper_configured
    helpers = list_credential_helpers()
  File "C:\PJFiles\Asset_Modeler\SDImageAi\RuinedFooocus\python_embeded\lib\site-packages\huggingface_hub\utils\_git_credential.py", line 50, in list_credential_helpers
    output = run_subprocess("git config --list", folder=folder).stdout
  File "C:\PJFiles\Asset_Modeler\SDImageAi\RuinedFooocus\python_embeded\lib\site-packages\huggingface_hub\utils\_subprocess.py", line 83, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>

**Comment by Pajamas720** [comment]
I found out how to enter the token lol. before i close this, was i supposed to make an environment from scratch or was there supposed to be a place where i could just paste the code?
