### ISSUE TITLE
RF does not install on Fedora 40

### ISSUE THREAD

**Issue by odevroed** [runew0lf/RuinedFooocus#194]
Hi, 

At the launch step, I get the error below. 

python launch.py
Python 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
RuinedFooocus version: 1.56.0
Check pip
Check pre-requirements
This next step may take a while
Installing required modules
Traceback (most recent call last):
  File "/home/olivier/AI/RuinedFooocus/launch.py", line 150, in <module>
    prepare_environment()
  File "/home/olivier/AI/RuinedFooocus/launch.py", line 78, in prepare_environment
    run_pip(f'install -r "{launch_pip_file}" --extra-index-url {torch_index_url}', "required modules")
  File "/home/olivier/AI/RuinedFooocus/modules/launch_util.py", line 97, in run_pip
    return run(
           ^^^^
  File "/home/olivier/AI/RuinedFooocus/modules/launch_util.py", line 90, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install required modules.
Command: "/home/olivier/AI/RuinedFooocus/venv/bin/python" -m pip install -r "pip_modules.txt" --extra-index-url https://download.pytorch.org/whl/cu121 --prefer-binary
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment
Collecting torch==2.2.2 (from -r pip_modules.txt (line 1))
  Using cached https://download.pytorch.org/whl/cu121/torch-2.2.2%2Bcu121-cp312-cp312-linux_x86_64.whl (757.2 MB)
Collecting torchvision==0.17.2 (from -r pip_modules.txt (line 2))
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.17.2%2Bcu121-cp312-cp312-linux_x86_64.whl (7.0 MB)
Collecting torchsde==0.2.6 (from -r pip_modules.txt (line 3))
  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Collecting einops==0.4.1 (from -r pip_modules.txt (line 4))
  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting transformers==4.44.0 (from -r pip_modules.txt (line 5))
  Using cached transformers-4.44.0-py3-none-any.whl.metadata (43 kB)
Collecting safetensors==0.4.3 (from -r pip_modules.txt (line 6))
  Using cached safetensors-0.4.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting accelerate==0.33.0 (from -r pip_modules.txt (line 7))
  Using cached accelerate-0.33.0-py3-none-any.whl.metadata (18 kB)
Collecting pyyaml==6.0 (from -r pip_modules.txt (line 8))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/olivier/AI/RuinedFooocus/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/olivier/AI/RuinedFooocus/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/olivier/AI/RuinedFooocus/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 108, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-dpm7kxyc/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
\u2502 exit code: 1
\u2570\u2500> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip

**Comment by yownas** [comment]
Python 3.12 might be an issue. We've only really tested it with python 3.10.

**Comment by odevroed** [comment]
Yup, that was it. Using 3.10 did the trick.

Thanks a lot
