### ISSUE TITLE
Custom OBP Key Error

### ISSUE THREAD

**Issue by mawaiidesu** [runew0lf/RuinedFooocus#196]
Hi there,

I'm getting a key error with the name of the custom prompt (saved as), when I am trying to generate a random prompt using a custom one button preset. Also happens with 'Instant OBP'

Traceback (most recent call last):
  File "python_embeded\lib\site-packages\gradio\queueing.py", line 407, in call_prediction output = await route_utils.call_process_api(
  File "python_embeded\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api output = await app.get_blocks().process_api(
  File "python_embeded\lib\site-packages\gradio\blocks.py", line 1550, in process_api result = await self.call_function(
  File "python_embeded\lib\site-packages\gradio\blocks.py", line 1185, in call_function prediction = await anyio.to_thread.run_sync(
  File "python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread(
  File "python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread return await future
  File "python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run result = context.run(func, *args)
  File "python_embeded\lib\site-packages\gradio\utils.py", line 661, in wrapper response = f(*args, **kwargs)
  File "RuinedFooocus\ui_onebutton.py", line 420, in gen_prompt prompt = build_dynamic_prompt(
  File "RuinedFooocus\random_prompt\build_dynamic_prompt.py", line 112, in build_dynamic_prompt selected_opb_preset = OBPresets.get_obp_preset(OBP_preset)
  File "RuinedFooocus\random_prompt\one_button_presets.py", line 41, in get_obp_preset return self.opb_presets[name]
KeyError: 'Photograph1'

**Comment by mawaiidesu** [comment]
NVM. Had to reload.
