### ISSUE TITLE
Recommended Setup for PixArt-Sigma-900M?

### ISSUE THREAD

**Issue by DavidDragonsage** [runew0lf/RuinedFooocus#205]
### Discussed in https://github.com/runew0lf/RuinedFooocus/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **DavidDragonsage** November  6, 2024</sup>
I noticed from the RF Wiki and also from the Changelog at Discord that PixArt-Sigma is supported. I installed 900M-base.safetensors to the base models (checkpoints) folder and model-00001-of-00002.safetensors to the clip folder but I got the error: "ERROR: Can only use SDXL, SD3 or Flux models"

How do I setup PixArt-Sigma properly?</div>

**Comment by DavidDragonsage** [comment]
**Console Log:** 

Loading base model: PixArt\900M-base.safetensors
Failed. Trying to load as Flux unet.
Loading base unet: E:\stable-diffusion-webui\models\Stable-diffusion\PixArt\900M-base.safetensors
Traceback (most recent call last):
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\sdxl_pipeline.py", line 282, in load_base_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(filename)
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\repositories\ComfyUI\comfy\sd.py", line 527, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: E:\stable-diffusion-webui\models\Stable-diffusion\PixArt\900M-base.safetensors

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\modules\sdxl_pipeline.py", line 231, in load_base_model
    unet = comfy.sd.load_diffusion_model(filename, model_options=model_options)
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\repositories\ComfyUI\comfy\sd.py", line 662, in load_diffusion_model
    model = load_diffusion_model_state_dict(sd, model_options=model_options)
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\repositories\ComfyUI\comfy\sd.py", line 629, in load_diffusion_model_state_dict
    model_config = model_detection.model_config_from_diffusers_unet(sd)
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\repositories\ComfyUI\comfy\model_detection.py", line 496, in model_config_from_diffusers_unet
    unet_config = unet_config_from_diffusers_unet(state_dict)
  File "F:\RuinedFooocus_win64_1-25-2\RuinedFooocus\repositories\ComfyUI\comfy\model_detection.py", line 372, in unet_config_from_diffusers_unet
    match["model_channels"] = state_dict["conv_in.weight"].shape[0]
KeyError: 'conv_in.weight'
Failed to load E:\stable-diffusion-webui\models\Stable-diffusion\PixArt\900M-base.safetensors
LoRAs loaded: []
ERROR: Can only use SDXL, SD3 or Flux models
Time taken: 0.00 seconds Pipeline process
ERROR: Can only use SDXL, SD3 or Flux models
Time taken: 0.00 seconds Pipeline process
ERROR: Can only use SDXL, SD3 or Flux models
Time taken: 0.00 seconds Pipeline process
ERROR: Can only use SDXL, SD3 or Flux models
Time taken: 0.00 seconds Pipeline process
ERROR: Can only use SDXL, SD3 or Flux models
Time taken: 0.00 seconds Pipeline process

**Comment by DavidDragonsage** [comment]
Problem solved! I discovered the proper installation procedure at the RF Wiki:
https://github.com/runew0lf/RuinedFooocus/wiki/Diffusers

Simply enter this in the prompt and press generate:
hf: dataautogpt3/PixArt-Sigma-900M

All will be well! 🙂
