### ISSUE TITLE
SD3.5 support

### ISSUE THREAD

**Issue by SUP3RMASS1VE** [runew0lf/RuinedFooocus#208]
any plans to add SD3.5 support?

or does  SD3.5 work but im doing somthing wrong? Lol

Loading base model: sd3.5_large_turbo.safetensors
WARNING:root:no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
Failed. Trying to load as Flux unet.
Loading base unet: F:\pinokio\api\RuinedFooocus.git\app\modules\..\models\checkpoints\sd3.5_large_turbo.safetensors
Loading CLIP clip_l.safetensors and clip_g.safetensors
Loading VAE sdxl_vae.safetensors
Base model loaded: F:\pinokio\api\RuinedFooocus.git\app\modules\..\models\checkpoints\sd3.5_large_turbo.safetensors
LoRAs loaded: []
  0%|                                                                                  | 0/30 [00:00<?, ?it/s]
Time taken: 5.11 seconds Pipeline process
Exception in thread Thread-7 (worker):
Traceback (most recent call last):
  File "F:\pinokio\bin\miniconda\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\pinokio\bin\miniconda\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\modules\async_worker.py", line 342, in worker
    handler(task)
  File "F:\pinokio\api\RuinedFooocus.git\app\modules\async_worker.py", line 57, in handler
    process(gen_data)
  File "F:\pinokio\api\RuinedFooocus.git\app\modules\async_worker.py", line 240, in process
    imgs = pipeline.process(
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\modules\sdxl_pipeline.py", line 711, in process
    samples = sampler.sample(
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 829, in sample      
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 729, in sample      
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed) 
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 716, in sample      
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 600, in sample      
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\k_diffusion\sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 299, in __call__    
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 682, in __call__    
    return self.predict_noise(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 934, in forward
    return super().forward(x, timesteps, context=context, y=y, control=control)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 912, in forward
    y = self.y_embedder(y)  # (N, D)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 256, in forward
    emb = self.mlp(x)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\ops.py", line 76, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "F:\pinokio\api\RuinedFooocus.git\app\repositories\ComfyUI\comfy\ops.py", line 72, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
  File "F:\pinokio\api\RuinedFooocus.git\app\env\lib\site-packages\torch\_tensor.py", line 1418, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1280 and 2048x2432)

**Comment by yownas** [comment]
SD 3 and 3.5 should be supported now.

**Comment by gerroon** [comment]
> SD 3 and 3.5 should be supported now.

I can't get 3.5 to work

https://github.com/runew0lf/RuinedFooocus/discussions/256
