### ISSUE TITLE
Error after start

### ISSUE THREAD

**Issue by Eleksar387** [runew0lf/RuinedFooocus#76]
After the last update it won't startup anymore. Error see below. 

F:\AI\RuinedFooocus_win641-0-0>run.bat

F:\AI\RuinedFooocus_win641-0-0>.\python_embeded\python.exe -s RuinedFooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
RuinedFooocus version: 1.17.2
Inference Engine exists.
Inference Engine checkout finished.
Traceback (most recent call last):
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\launch.py", line 212, in <module>
    from webui import *
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\webui.py", line 9, in <module>
    import modules.async_worker as worker
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\async_worker.py", line 8, in <module>
    import modules.controlnet
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\controlnet.py", line 89, in <module>
    controlnet_settings = load_cnsettings()
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\controlnet.py", line 34, in load_cnsettings
    settings.update(json.load(f))
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 59 column 17 (char 1002)

F:\AI\RuinedFooocus_win641-0-0>pause

**Comment by runew0lf** [comment]
Please join the discord so we can discusss further

**Comment by emotionaldreams** [comment]
having same exact issue after update to recent. why can't it be answered here where issues are reported? don't have a discord account.

**Comment by runew0lf** [comment]
i dont have a github account sorry

**Comment by emotionaldreams** [comment]
? couldn't just answer it  with your reply? oh well. alright. i'll just go back to original Fooocus(or A1111)

**Comment by runew0lf** [comment]
> ? u couldn't just answer it with your reply? oh well. alright. i'll just go back to original Fooocus(or A1111)

thats the wonders of free software and forks etc, you can choose whatever software you like!! take care *mwa*
