### ISSUE TITLE
cv2 Missing

### ISSUE THREAD

**Issue by drdancm** [runew0lf/RuinedFooocus#92]
Problem running under Stability Matrix:

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
RuinedFooocus version: 1.26.0
Comfy Backend exists.
Comfy Backend update finished.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\STABLEDIFF\Data\Packages\RuinedFooocus\modules\async_worker.py", line 31, in worker
    import modules.pipelines
  File "D:\STABLEDIFF\Data\Packages\RuinedFooocus\modules\pipelines.py", line 4, in <module>
    import modules.sdxl_pipeline as sdxl_pipeline
  **File "D:\STABLEDIFF\Data\Packages\RuinedFooocus\modules\sdxl_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'**
Total VRAM 24575 MB, total RAM 130768 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

**Comment by yownas** [comment]
Just pushed an update, it might work better now. :)

**Comment by SilverAmerican** [comment]
Same error on my end still

**Comment by drdancm** [comment]
I'm afraid the cv2 problem was not solved with the latest update:

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
RuinedFooocus version: 1.26.0
Comfy Backend exists.
Comfy Backend update finished.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\STABLEDIFF\Data\Packages\RuinedFooocus\modules\async_worker.py", line 31, in worker
    import modules.pipelines
  File "D:\STABLEDIFF\Data\Packages\RuinedFooocus\modules\pipelines.py", line 4, in <module>
    import modules.sdxl_pipeline as sdxl_pipeline
  File "D:\STABLEDIFF\Data\Packages\RuinedFooocus\modules\sdxl_pipeline.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Total VRAM 24575 MB, total RAM 130768 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()

**Comment by yownas** [comment]
Not sure what happens. I've never used Stability Matrix.
It has been added to the requirements-version.txt which should be checked each time you run launch.py

can you check to see if you have `opencv-python==4.8.1.78` at the end of requirements-version.txt?

**Comment by runew0lf** [comment]
this looks like an installation issue with stability maxtrix, i recommend you log a support ticket with them.
