### ISSUE TITLE
support for vega?

### ISSUE THREAD

**Issue by Ramam001** [runew0lf/RuinedFooocus#94]
yes, vega https://huggingface.co/segmind/Segmind-Vega

does your ui supports this?

**Comment by runew0lf** [comment]
yeah it does

**Comment by Ramam001** [comment]
Then why loading this model or other models take ages and saying

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
RuinedFooocus version: 1.26.0
Comfy Backend exists.
Comfy Backend update finished.
Total VRAM 4096 MB, total RAM 14188 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
xformers version: 0.0.20
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Loading base model: sd_xl_base_1.0_0.9vae.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
Loading base model: xxmix9realisticsdxl_v10.safetensors
Failed to load xxmix9realisticsdxl_v10.safetensors, loading default model instead
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "G:\Data\Packages\RuinedFooocus\modules\sdxl_pipeline.py", line 130, in load_base_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(filename)
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 451, in load_checkpoint_guess_config
    model = model_config.get_model(sd, "model.diffusion_model.", device=inital_load_device)
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\supported_models.py", line 173, in get_model
    out = model_base.SDXL(self, model_type=self.model_type(state_dict, prefix), device=device)
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_base.py", line 260, in __init__
    super().__init__(model_config, model_type, device=device)
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_base.py", line 46, in __init__
    self.diffusion_model = UNetModel(**unet_config, device=device)
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 746, in __init__
    get_resblock(
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 605, in get_resblock
    return ResBlock(
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 182, in __init__
    operations.conv_nd(dims, channels, self.out_channels, kernel_size, padding=padding, dtype=dtype, device=device),
  File "G:\Data\Packages\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ops.py", line 26, in conv_nd
    return Conv2d(*args, **kwargs)
  File "G:\Data\Packages\RuinedFooocus\venv\lib\site-packages\torch\nn\modules\conv.py", line 450, in __init__
    super().__init__(
  File "G:\Data\Packages\RuinedFooocus\venv\lib\site-packages\torch\nn\modules\conv.py", line 137, in __init__
    self.weight = Parameter(torch.empty(
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "G:\Data\Packages\RuinedFooocus\modules\async_worker.py", line 311, in worker
    handler(task)
  File "G:\Data\Packages\RuinedFooocus\modules\async_worker.py", line 56, in handler
    process(gen_data)
  File "G:\Data\Packages\RuinedFooocus\modules\async_worker.py", line 103, in process
    gen_data["modelhash"] = pipeline.load_base_model(gen_data["base_model_name"])
  File "G:\Data\Packages\RuinedFooocus\modules\sdxl_pipeline.py", line 149, in load_base_model
    load_base_model(path_manager.default_model_names["default_base_model_name"])
NameError: name 'load_base_model' is not defined



Default model works fine but not other for some reason, I'm using stable matrix( with comfy ui)
